# Generated by Django 5.2.3 on 2025-06-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sock',
        ),
    ]
